theme: jekyll-theme-minimal
title: Owen's Blog
description: Blog about the creation of my financial LLM
lsi: false
safe: true
source: [andreaseno.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

